# (PART) Tilstandsregnskap {-}



# Økologisk tilstand

**Mer tekst kommer snart...**


En kort definisjon....

Økologisk tilstand er en holistisk vurdering av økosystemenes integritet. I praksis betyr ofte det i hvor stor grad økosystemene er påvirket av mennesker. Tilstanden vurderes ved hjelp av et indikatorsett. 

I det norske fagsystemet for økologiskl tilstand [@Nybø2017] er det definert syv egenskaer ved økosystemene som bør dekkes best mulig gjennom indikatorsettet.
I FN-standarden [@UN2021] brukes det seks tilsvarende genskaper, såkalt ECT-klasser eller *Ecosystem Condition Typology classes*, og det er disse som vi benytter oss av i arbeidet i Nordre Follo, se Figur \@ref(fig:workflow). 
Som en tommelfingelregel bør hver ECT-klasse dekkes med minst en indikator per økosystem, og det bør være ca. 6-10 indikatore totalt per økosystem.
Se [@UN2021] for alle ytteligere definisjoner.







## FN-standarden for tilstandsregnskap

Introduksjon til tilstandsregnskap etter SEEA EA standarden

**Kommer snart....**
Litt om de andre delene av et naturregnskap




## Relevant nasjonalt utviklingsarbeid

Det er utgitt nasjonale økologiske tilstandsvurderinger for skog [@Framstad2021] og fjell [@Framstad2022] basert på samme grunnleggende metode som det som brukes i Nordre Follo (indeksmetoden) [@Jakobsson2021]. Disse følger på fra arbeidet med fagsystemet for økologisk tilstand [@Nybø2017].

